name: CI/CD

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest           #we need to provide Vm or container/runner where will run the written instruction

    steps:
      - name: Checkout repository       #check out the repo
        uses: actions/checkout@v4

      - name: Set up Go 1.22                  #set up go lang env
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build                                #build
        run: go build -o go-web-app

      - name: Test                          #test with provided test cases
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run golangci-lint                           #static code analysis /code quality
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10

  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker secret fingerprint
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "Username fingerprint:"
          printf '%s' "$DOCKERHUB_USERNAME" | sha256sum

          echo "Token fingerprint:"
          printf '%s' "$DOCKERHUB_TOKEN" | sha256sum

      - name: Login to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          TOKEN=$(printf '%s' "$DOCKERHUB_TOKEN" | tr -d '\r\n')
          printf '%s' "$TOKEN" | docker login docker.io \
            --username "$DOCKERHUB_USERNAME" \
            --password-stdin

      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.run_id }}  #everytime new tag like v1 v2 162738 or soemthing else  and asoonas image tag updates means something updated so argocd pulls and deploy on kubernetes cluster

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/go-web-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "shruti11091@gmail.com"
          git config --global user.name "shruti11091"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push